--
-- PostgreSQL database dump
--

\restrict vfmTWqg4zLbbgU5nbMbKbjKnIm9LpQhLqwmv45GrypJZE4nA6LaEHbqnRfl3TOQ

-- Dumped from database version 16.11 (Ubuntu 16.11-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.11 (Ubuntu 16.11-0ubuntu0.24.04.1)

-- Started on 2025-12-18 10:22:10 MSK

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 7 (class 2615 OID 24581)
-- Name: scheme; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA scheme;


ALTER SCHEMA scheme OWNER TO postgres;

--
-- TOC entry 2 (class 3079 OID 16390)
-- Name: btree_gist; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA public;


--
-- TOC entry 3833 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION btree_gist; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION btree_gist IS 'support for indexing common datatypes in GiST';


--
-- TOC entry 1064 (class 1247 OID 17041)
-- Name: subscription_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.subscription_status AS ENUM (
    'trialing',
    'active',
    'canceled',
    'expired',
    'suspended',
    'refunded',
    'past_due'
);


ALTER TYPE public.subscription_status OWNER TO postgres;

--
-- TOC entry 1067 (class 1247 OID 17056)
-- Name: watch_event_type; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.watch_event_type AS ENUM (
    'start',
    'pause',
    'seek',
    'progress',
    'complete'
);


ALTER TYPE public.watch_event_type OWNER TO postgres;

--
-- TOC entry 1070 (class 1247 OID 17068)
-- Name: watch_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.watch_status AS ENUM (
    'in_progress',
    'completed',
    'abandoned'
);


ALTER TYPE public.watch_status OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 17076)
-- Name: app_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    username text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.app_user OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 17075)
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 17186)
-- Name: promo_code; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.promo_code (
    id bigint NOT NULL,
    code text NOT NULL,
    description text,
    bonus_days integer DEFAULT 0 NOT NULL,
    overrides_plan_id bigint,
    valid_from timestamp with time zone,
    valid_to timestamp with time zone,
    max_uses_total integer,
    max_uses_per_user integer,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT promo_code_bonus_days_check CHECK ((bonus_days >= 0)),
    CONSTRAINT promo_code_max_uses_per_user_check CHECK (((max_uses_per_user IS NULL) OR (max_uses_per_user >= 1))),
    CONSTRAINT promo_code_max_uses_total_check CHECK (((max_uses_total IS NULL) OR (max_uses_total >= 1)))
);


ALTER TABLE public.promo_code OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 17185)
-- Name: promo_code_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.promo_code ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.promo_code_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 17236)
-- Name: subscription_event; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subscription_event (
    id bigint NOT NULL,
    user_subscription_id bigint NOT NULL,
    event_type text NOT NULL,
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    meta jsonb DEFAULT '{}'::jsonb NOT NULL
);


ALTER TABLE public.subscription_event OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 17235)
-- Name: subscription_event_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subscription_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 17172)
-- Name: subscription_plan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subscription_plan (
    id bigint NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    base_duration_days integer DEFAULT 30 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT subscription_plan_base_duration_days_check CHECK ((base_duration_days > 0))
);


ALTER TABLE public.subscription_plan OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17171)
-- Name: subscription_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subscription_plan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 17097)
-- Name: subtitle_track; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subtitle_track (
    id bigint NOT NULL,
    video_id bigint NOT NULL,
    language text DEFAULT 'und'::text NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    content jsonb NOT NULL,
    generated_at timestamp with time zone DEFAULT now() NOT NULL,
    size_bytes integer,
    CONSTRAINT subtitle_track_size_bytes_check CHECK (((size_bytes IS NULL) OR (size_bytes >= 0))),
    CONSTRAINT subtitle_track_version_check CHECK ((version >= 1))
);


ALTER TABLE public.subtitle_track OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 17096)
-- Name: subtitle_track_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subtitle_track ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subtitle_track_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 17207)
-- Name: user_subscription; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_subscription (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    plan_id bigint NOT NULL,
    promo_code_id bigint,
    period tstzrange NOT NULL,
    status public.subscription_status DEFAULT 'active'::public.subscription_status NOT NULL,
    purchased_at timestamp with time zone DEFAULT now() NOT NULL,
    activated_at timestamp with time zone,
    canceled_at timestamp with time zone,
    note text
);


ALTER TABLE public.user_subscription OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 17206)
-- Name: user_subscription_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_subscription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_subscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 17251)
-- Name: v_user_current_subscription; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.v_user_current_subscription AS
 SELECT us.user_id,
    us.id AS user_subscription_id,
    us.status,
    us.period,
    us.purchased_at,
    us.activated_at,
    us.canceled_at,
    COALESCE(pc.overrides_plan_id, us.plan_id) AS effective_plan_id,
    sp.code AS effective_plan_code,
    sp.name AS effective_plan_name,
    us.promo_code_id
   FROM ((public.user_subscription us
     LEFT JOIN public.promo_code pc ON ((pc.id = us.promo_code_id)))
     JOIN public.subscription_plan sp ON ((sp.id = COALESCE(pc.overrides_plan_id, us.plan_id))))
  WHERE ((us.status = ANY (ARRAY['trialing'::public.subscription_status, 'active'::public.subscription_status, 'past_due'::public.subscription_status])) AND (now() <@ us.period));


ALTER VIEW public.v_user_current_subscription OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 17087)
-- Name: video; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.video (
    id bigint NOT NULL,
    title text,
    duration_sec integer,
    source text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT video_duration_sec_check CHECK (((duration_sec IS NULL) OR (duration_sec >= 0)))
);


ALTER TABLE public.video OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 17119)
-- Name: watch_event; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.watch_event (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    video_id bigint NOT NULL,
    event_type public.watch_event_type NOT NULL,
    timecode_sec integer NOT NULL,
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    subtitle_track_id bigint,
    meta jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT watch_event_timecode_sec_check CHECK ((timecode_sec >= 0))
);


ALTER TABLE public.watch_event OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 17118)
-- Name: watch_event_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.watch_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.watch_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 17146)
-- Name: watch_progress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.watch_progress (
    user_id bigint NOT NULL,
    video_id bigint NOT NULL,
    last_timecode_sec integer DEFAULT 0 NOT NULL,
    last_viewed_at timestamp with time zone DEFAULT now() NOT NULL,
    status public.watch_status DEFAULT 'in_progress'::public.watch_status NOT NULL,
    subtitle_track_id bigint,
    CONSTRAINT watch_progress_last_timecode_sec_check CHECK ((last_timecode_sec >= 0))
);


ALTER TABLE public.watch_progress OWNER TO postgres;

--
-- TOC entry 3637 (class 2606 OID 17084)
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- TOC entry 3639 (class 2606 OID 17086)
-- Name: app_user app_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_username_key UNIQUE (username);


--
-- TOC entry 3660 (class 2606 OID 17200)
-- Name: promo_code promo_code_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.promo_code
    ADD CONSTRAINT promo_code_code_key UNIQUE (code);


--
-- TOC entry 3662 (class 2606 OID 17198)
-- Name: promo_code promo_code_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.promo_code
    ADD CONSTRAINT promo_code_pkey PRIMARY KEY (id);


--
-- TOC entry 3670 (class 2606 OID 17244)
-- Name: subscription_event subscription_event_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscription_event
    ADD CONSTRAINT subscription_event_pkey PRIMARY KEY (id);


--
-- TOC entry 3656 (class 2606 OID 17184)
-- Name: subscription_plan subscription_plan_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscription_plan
    ADD CONSTRAINT subscription_plan_code_key UNIQUE (code);


--
-- TOC entry 3658 (class 2606 OID 17182)
-- Name: subscription_plan subscription_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscription_plan
    ADD CONSTRAINT subscription_plan_pkey PRIMARY KEY (id);


--
-- TOC entry 3644 (class 2606 OID 17108)
-- Name: subtitle_track subtitle_track_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subtitle_track
    ADD CONSTRAINT subtitle_track_pkey PRIMARY KEY (id);


--
-- TOC entry 3646 (class 2606 OID 17110)
-- Name: subtitle_track subtitle_track_video_id_language_version_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subtitle_track
    ADD CONSTRAINT subtitle_track_video_id_language_version_key UNIQUE (video_id, language, version);


--
-- TOC entry 3664 (class 2606 OID 17234)
-- Name: user_subscription user_subscription_no_overlap; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_subscription
    ADD CONSTRAINT user_subscription_no_overlap EXCLUDE USING gist (user_id WITH =, period WITH &&) WHERE ((status = ANY (ARRAY['trialing'::public.subscription_status, 'active'::public.subscription_status, 'past_due'::public.subscription_status])));


--
-- TOC entry 3667 (class 2606 OID 17215)
-- Name: user_subscription user_subscription_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_subscription
    ADD CONSTRAINT user_subscription_pkey PRIMARY KEY (id);


--
-- TOC entry 3641 (class 2606 OID 17095)
-- Name: video video_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.video
    ADD CONSTRAINT video_pkey PRIMARY KEY (id);


--
-- TOC entry 3649 (class 2606 OID 17128)
-- Name: watch_event watch_event_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.watch_event
    ADD CONSTRAINT watch_event_pkey PRIMARY KEY (id);


--
-- TOC entry 3653 (class 2606 OID 17154)
-- Name: watch_progress watch_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.watch_progress
    ADD CONSTRAINT watch_progress_pkey PRIMARY KEY (user_id, video_id);


--
-- TOC entry 3671 (class 1259 OID 17250)
-- Name: subscription_event_sub_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX subscription_event_sub_idx ON public.subscription_event USING btree (user_subscription_id, occurred_at DESC);


--
-- TOC entry 3642 (class 1259 OID 17117)
-- Name: subtitle_track_content_gin; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX subtitle_track_content_gin ON public.subtitle_track USING gin (content);


--
-- TOC entry 3647 (class 1259 OID 17116)
-- Name: subtitle_track_video_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX subtitle_track_video_idx ON public.subtitle_track USING btree (video_id);


--
-- TOC entry 3665 (class 1259 OID 17232)
-- Name: user_subscription_period_gist; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_subscription_period_gist ON public.user_subscription USING gist (user_id, period);


--
-- TOC entry 3668 (class 1259 OID 17231)
-- Name: user_subscription_user_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_subscription_user_idx ON public.user_subscription USING btree (user_id, purchased_at DESC);


--
-- TOC entry 3650 (class 1259 OID 17144)
-- Name: watch_event_user_time_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX watch_event_user_time_idx ON public.watch_event USING btree (user_id, occurred_at DESC);


--
-- TOC entry 3651 (class 1259 OID 17145)
-- Name: watch_event_user_video_time_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX watch_event_user_video_time_idx ON public.watch_event USING btree (user_id, video_id, occurred_at DESC);


--
-- TOC entry 3654 (class 1259 OID 17170)
-- Name: watch_progress_user_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX watch_progress_user_idx ON public.watch_progress USING btree (user_id, last_viewed_at DESC);


--
-- TOC entry 3679 (class 2606 OID 17201)
-- Name: promo_code promo_code_overrides_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.promo_code
    ADD CONSTRAINT promo_code_overrides_plan_id_fkey FOREIGN KEY (overrides_plan_id) REFERENCES public.subscription_plan(id) ON DELETE SET NULL;


--
-- TOC entry 3683 (class 2606 OID 17245)
-- Name: subscription_event subscription_event_user_subscription_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscription_event
    ADD CONSTRAINT subscription_event_user_subscription_id_fkey FOREIGN KEY (user_subscription_id) REFERENCES public.user_subscription(id) ON DELETE CASCADE;


--
-- TOC entry 3672 (class 2606 OID 17111)
-- Name: subtitle_track subtitle_track_video_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subtitle_track
    ADD CONSTRAINT subtitle_track_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.video(id) ON DELETE CASCADE;


--
-- TOC entry 3680 (class 2606 OID 17221)
-- Name: user_subscription user_subscription_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_subscription
    ADD CONSTRAINT user_subscription_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plan(id) ON DELETE RESTRICT;


--
-- TOC entry 3681 (class 2606 OID 17226)
-- Name: user_subscription user_subscription_promo_code_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_subscription
    ADD CONSTRAINT user_subscription_promo_code_id_fkey FOREIGN KEY (promo_code_id) REFERENCES public.promo_code(id) ON DELETE SET NULL;


--
-- TOC entry 3682 (class 2606 OID 17216)
-- Name: user_subscription user_subscription_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_subscription
    ADD CONSTRAINT user_subscription_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- TOC entry 3673 (class 2606 OID 17139)
-- Name: watch_event watch_event_subtitle_track_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.watch_event
    ADD CONSTRAINT watch_event_subtitle_track_id_fkey FOREIGN KEY (subtitle_track_id) REFERENCES public.subtitle_track(id) ON DELETE SET NULL;


--
-- TOC entry 3674 (class 2606 OID 17129)
-- Name: watch_event watch_event_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.watch_event
    ADD CONSTRAINT watch_event_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- TOC entry 3675 (class 2606 OID 17134)
-- Name: watch_event watch_event_video_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.watch_event
    ADD CONSTRAINT watch_event_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.video(id) ON DELETE CASCADE;


--
-- TOC entry 3676 (class 2606 OID 17165)
-- Name: watch_progress watch_progress_subtitle_track_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.watch_progress
    ADD CONSTRAINT watch_progress_subtitle_track_id_fkey FOREIGN KEY (subtitle_track_id) REFERENCES public.subtitle_track(id) ON DELETE SET NULL;


--
-- TOC entry 3677 (class 2606 OID 17155)
-- Name: watch_progress watch_progress_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.watch_progress
    ADD CONSTRAINT watch_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- TOC entry 3678 (class 2606 OID 17160)
-- Name: watch_progress watch_progress_video_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.watch_progress
    ADD CONSTRAINT watch_progress_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.video(id) ON DELETE CASCADE;


-- Completed on 2025-12-18 10:22:10 MSK

--
-- PostgreSQL database dump complete
--

\unrestrict vfmTWqg4zLbbgU5nbMbKbjKnIm9LpQhLqwmv45GrypJZE4nA6LaEHbqnRfl3TOQ

